name: Lint
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
jobs:
  test:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '12.x'
      - run: npm install
      - run: npm run lint