name: Update dist file
on:
  push:
    branches: [main]
jobs:
  test:
    name: Update dist file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '12.x'
      - run: npm install
      - run: npm run dist
      - uses: ./
        with:
          file-path: dist/index.js
          commit-msg: Update dist file
          github-token: ${{ secrets.GITHUB_TOKEN }}